language: csharp
solution: "./Travis.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./Travis.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild ./Travis.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Travis.Tests/bin/Debug/Travis.Tests.dll